SWEP.Category = "M9K Specialties"
SWEP.PrintName = "Smoke Grenade"
SWEP.Slot = 4
SWEP.SlotPos = 5
SWEP.Weight = 10
SWEP.DrawCrosshair = false
SWEP.HoldType = "grenade"
SWEP.ViewModelFOV = 75
SWEP.ViewModelFlip = true
SWEP.ViewModel = "models/weapons/v_eq_smokegrenade.mdl"
SWEP.WorldModel	= Model("models/weapons/w_eq_smokegrenade.mdl")
SWEP.Base = "mg_nade_base"
SWEP.Spawnable = true
SWEP.AdminSpawnable = true
SWEP.Primary.ClipSize = 1
SWEP.Primary.DefaultClip = 1
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "smoke_grenade"	
SWEP.Primary.Round = "m9k_thrown_smoke"
SWEP.DetonateTime = 5
SWEP.Explode = true
SWEP.WeaponType = "grenade"