-- Pointshop | Playermodel Fix

local PS_PMModPos = {
	["Kopfbedeckungen"] = {
		["models/player_sinonsao.mdl"] = {-4.89, 0, 5.5},
		["models/player/donald_trump.mdl"] = {-3.82, -0.7, 4.23},
		["models/player/combine_soldier.mdl"] = {-6, 0, 3.8},
		["models/minson97/hitler/hitler.mdl"] = {-3.25, 0, 3.61},
		["models/player/hw_link.mdl"] = {-4.25, 0, 7.65},
		["models/player/rick/rick.mdl"] = {-3.21, -0.3, 10.34},
		["models/player/skeleton.mdl"] = {-3.5, 0, 5},
		["models/player/optimus_prime.mdl"] = {-3.5, 0, 1.4},
		["models/player/thomasdankassengine.mdl"] = {-3.32, 0, 4.5},
		["models/player/guerilla.mdl"] = {-4, 0, 5.63},
		["models/player/bond.mdl"] = {-3.47, -0.05, 7.89},
		["models/player/anon/anon.mdl"] = {-5.32, 0, 6.33},
		["models/player/urban.mdl"] = {-3, 0, 6.93},
		["models/player/stanmcg/tvhead/tvhead_playermodel.mdl"] = {-7.32, 0, 13.5},
		["models/code_gs/50cent/50centplayer.mdl"] = {-3.71, 0, 4.84},
		["models/player/bigsmoke/smoke.mdl"] = {-4.21, 0, 4.94},
		["models/player/combine_super_soldier.mdl"] = {-6, 0, 4.9},
		["models/player/arctic.mdl"] = {-3, 0, 5.83},
		["models/player/leet.mdl"] = {-3, 0, 6.33},
		["models/player/bobert/aojoker.mdl"] = {-4.21, 0, 3.64},
		["models/player/pyroteknik/shulk.mdl"] = {-5.22, 0, 9},
		["models/vinrax/player/scp049_player.mdl"] = {-6.32, 0, 5.43},
		["models/gin_ibushi/oc/rstar/gin_ibushi/gin_ibushi.mdl"] = {-4, 0, 8.26},
		["models/player/chewie.mdl"] = {-4.32, 0.55, 4.83},
		["models/player/soldier_stripped.mdl"] = {-4.1, 0, 2},
		["models/player/cj.mdl"] = {-4.62, 0, 1.83},
		["models/player/kermit.mdl"] = {-0.02, 0, 12},
		["models/player/deckboy/storm_trooper_pm/storm_trooper_pm.mdl"] = {-4.21, 0, 4.5},
		["models/player/old_snake.mdl"] = {-4.3, -0.05, 2.73},
		["models/player_moxxi.mdl"] = {-5.0, 2.0, 9.5},
		["models/player/dewobedil/girls_frontline/hk416/default_p.mdl"] = {-1.0, 0, 5.9},
		["models/captainbigbutt/vocaloid/luka.mdl"] = {-4.29, 0, 3.57},
		["models/player/luke_skywalker.mdl"] = {-4.0, 0, 4.6},
		["models/player/h3_masterchief_player.mdl"] = {-4.1, 0, 4.7},
		["models/raptor_player/raptor_player.mdl"] = {-2.82, 0, 6},
		["models/player/screamplayermodel/scream/scream.mdl"] = {-3, 0, 4.8},
		["models/player/voikanaa/snoop_dogg.mdl"] = {-4.32, 0, 3.53},
		["models/player/vanoss/evan.mdl"] = {-3.98, 0, 6},
		["models/player/charple.mdl"] = {-4.5, 0, 2},
		["models/player/lord_voldemort.mdl"] = {-4.32, 0, 4.13},
		["models/player/superheroes/superman.mdl"] = {-4.32, 0, 6.83},
		["models/mark2580/borderlands_ps/jack_bl_ps.mdl"] = {-3.9, 0, 5.0},
		["models/batman/slow/jamis/mkvsdcu/batman/slow_pub_v2.mdl"] = {-4.21, 0, 5.34},
		["models/juliet.mdl"] = {-3.58, 0, 3.48},
		["models/player/christmas/santa.mdl"] = {-3.4, 0, 5.5},
		["models/player/corpse1.mdl"] = {-3.5, 0, 3},
		["models/ninja/vaas.mdl"] = {-4.32, 0, 3.13},
		["models/player_compa.mdl"] = {-3.7, 0, 4.1},
		["models/jazzmcfly/brs/brs.mdl"] = {-4.5, 0, 6.26},
		["models/player/lich_king_wow_masked.mdl"] = {-4.9, -0.8, 5.62},
		["models/player_noire.mdl"] = {-3.1, 0, 4.2},
		["models/player/han_solo.mdl"] = {-4.22, 0, 3.43},
		["models/player/e3assassin.mdl"] = {-3.89, 0, 4.69},
		["models/player/demon_violinist/demon_violinist.mdl"] = {-4.32, 0, 5.23},
		["models/player/police_fem.mdl"] = {-5.06, 0, 2.15},
		["models/player/lich_king_wow_maskless.mdl"] = {-4.2, -0.8, 5.0},
		["models/squall/squall.mdl"] = {-4.21, 0, 3.64},
		["models/player/gasmask.mdl"] = {-3, 0, 6,83},
		["models/captainbigbutt/vocaloid/miku_classic.mdl"] = {-4.0, 0, 5.96},
		["models/player/riot.mdl"] = {-3.2, 0, 6.83},
		["models/player/police.mdl"] = {-4.56, 0, 4.15},
		["models/jessev92/kuma/characters/osama_ply.mdl"] = {-5.0, 0, 4.0},
		["models/player/phoenix.mdl"] = {-3, 0, 5.63},
		["models/player/combine_soldier_prisonguard.mdl"] = {-6, 0, 3.8},
		["models/player/swat.mdl"] = {-3, 0, 6.53},
		["models/polycapn/bill_cipher.mdl"] = {-5.5, 0.7, 27.59},
		["models/datboi/datboi_reference.mdl"] = {-5, 0, 8},
		["models/player/zombie_fast.mdl"] = {-4, -0.5, 1}
	},

	["Brillen"] = {
		["models/player_sinonsao.mdl"] = {-3, 0, -1.11},
		["models/player/donald_trump.mdl"] = {-2, -0.37, -0.1},
		["models/minson97/hitler/hitler.mdl"] = {-1.5, 0, -0.5},
		["models/player/hw_link.mdl"] = {-1.7, 0, -0.4},
		["models/player/rick/rick.mdl"] = {0.5, -0.3, 4.5},
		["models/player/skeleton.mdl"] = {-2.2, 0, 1},
		["models/player/optimus_prime.mdl"] = {-2, 0.1, -2.5},
		["models/player/thomasdankassengine.mdl"] = {3, 0, -0.8},
		["models/player/guerilla.mdl"] = {-0.9, 0, 1},
		["models/player/bond.mdl"] = {-1.3, -0.05, 2.75},
		["models/player/anon/anon.mdl"] = {-1.25, 0, 1.87},
		["models/player/urban.mdl"] = {-0.9, 0, 0.6},
		["models/player/stanmcg/tvhead/tvhead_playermodel.mdl"] = {1.5, 2.0, 6.0},
		["models/code_gs/50cent/50centplayer.mdl"] = {-1.29, 0, 0},
		["models/player/bigsmoke/smoke.mdl"] = {-2, 0, 1},
		["models/player/arctic.mdl"] = {-0.9, 0, 1},
		["models/player/leet.mdl"] = {-0.9, 0, 1},
		["models/player/bobert/aojoker.mdl"] = {-2, 0, -1.3},
		["models/player/pyroteknik/shulk.mdl"] = {-2, 0, 1.54},
		["models/vinrax/player/scp049_player.mdl"] = {-3, 0, 0},
		["models/gin_ibushi/oc/rstar/gin_ibushi/gin_ibushi.mdl"] = {-2, 0, 1.46},
		["models/player/chewie.mdl"] = {-2, 0.55, -0.4},
		["models/player/soldier_stripped.mdl"] = {-2, 0, -1.5},
		["models/player/cj.mdl"] = {-3, 0, -0.95},
		["models/player/kermit.mdl"] = {4, 0, 9},
		["models/player/deckboy/storm_trooper_pm/storm_trooper_pm.mdl"] = {0, 0, -0.5},
		["models/player/old_snake.mdl"] = {-2.25, -0.05, -1.27},
		["models/player_moxxi.mdl"] = {-1.9, 0, 0},
		["models/player/dewobedil/girls_frontline/hk416/default_p.mdl"] = {0, 0, -0.5},
		["models/captainbigbutt/vocaloid/luka.mdl"] = {-3, 0, -2.73},
		["models/player/luke_skywalker.mdl"] = {-2.5, 0, -0.32},
		["models/player/h3_masterchief_player.mdl"] = {-1, 0, -0.55},
		["models/raptor_player/raptor_player.mdl"] = {4, 0, 2},
		["models/player/screamplayermodel/scream/scream.mdl"] = {-1.5, 0, 0},
		["models/player/voikanaa/snoop_dogg.mdl"] = {-2.25, 0, -0.2},
		["models/player/vanoss/evan.mdl"] = {0.5, 0, -0.3},
		["models/player/charple.mdl"] = {-3, 0, -0.5},
		["models/player/lord_voldemort.mdl"] = {-1.75, 0, -0.3},
		["models/player/superheroes/superman.mdl"] = {-2, 0, 2.53},
		["models/mark2580/borderlands_ps/jack_bl_ps.mdl"] = {-1.75, 0, -0.2},
		["models/batman/slow/jamis/mkvsdcu/batman/slow_pub_v2.mdl"] = {-1.8, 0, 1.4},
		["models/juliet.mdl"] = {-2.25, 0, -0.62},
		["models/player/christmas/santa.mdl"] = {-0.75, 0, -1.5},
		["models/player/corpse1.mdl"] = {-1.75, 0, 0},
		["models/ninja/vaas.mdl"] = {-2.25, 0, -1},
		["models/player_compa.mdl"] = {-1.25, 0, -3.25},
		["models/jazzmcfly/brs/brs.mdl"] = {-3, 0, 0.5},
		["models/player/lich_king_wow_masked.mdl"] = {-2, -0.8, 0.8},
		["models/player_noire.mdl"] = {-1, 0, -4},
		["models/player/han_solo.mdl"] = {-2.5, 0, -0.87},
		["models/player/e3assassin.mdl"] = {-2, 0, 0.79},
		["models/player/demon_violinist/demon_violinist.mdl"] = {-1.25, 0, -0.5},
		["models/player/police_fem.mdl"] = {-2.44, 0, -2},
		["models/player/lich_king_wow_maskless.mdl"] = {-3, -0.8, 0.8},
		["models/squall/squall.mdl"] = {-3.5, 0, -0.86},
		["models/player/gasmask.mdl"] = {0.2, 0, 1},
		["models/captainbigbutt/vocaloid/miku_classic.mdl"] = {-3, 0, 0},
		["models/player/riot.mdl"] = {-0.9, 0, 1},
		["models/jessev92/kuma/characters/osama_ply.mdl"] = {-3, 0, -0.8},
		["models/player/phoenix.mdl"] = {-0.9, 0, 1},
		["models/player/swat.mdl"] = {-0.9, 0, 0.6},
		["models/polycapn/bill_cipher.mdl"] = {-3.97, 0.7, 8.09},
		["models/datboi/datboi_reference.mdl"] = {1.5, 0, 6.04},
		["models/player/zombie_fast.mdl"] = {-2.5, 0, -0.5}
	}
}

local EquipTable
local reg = debug.getregistry()
local GetModel = reg.Entity.GetModel
function PS_CheckPMMods(ply, group)
    EquipTable = PS_PMModPos[group]
    if !EquipTable then return false end

    local EquipVector = PS.HoverModel and EquipTable[PS.Items[PS.HoverModel].Model]
    if EquipVector then
        return EquipVector
    end

    local model = GetModel(ply)
    if EquipTable[model] then
        return EquipTable[model]
    end

    return false
end 