local function ModernGamingOptions(CPanel)
	CPanel:AddControl("Label", {Text = "HUD:"})
	CPanel:AddControl("CheckBox", {Label = "HUD anzeigen", Command = "cl_drawhud"})
	CPanel:AddControl("CheckBox", {Label = "Spielerinformationen über den Köpfen von Spielern", Command = "bf_showhud"})
	CPanel:AddControl("CheckBox", {Label = "Spielerinformationen ohne Farbe darstellen", Command = "bf_whitename"})
	CPanel:AddControl("CheckBox", {Label = "Spielzeit anzeigen", Command = "utime_enable"})
	CPanel:AddControl("CheckBox", {Label = "Spawnschutzinformationen anzeigen", Command = "cl_drawspawninfo"})
	CPanel:AddControl("CheckBox", {Label = "Levelleiste anzeigen", Command = "cl_showlevelbar"})
	CPanel:AddControl("CheckBox", {Label = "Levelaufstiegsbenachrichtigungen anzeigen", Command = "cl_showlevelup"})
	CPanel:AddControl("CheckBox", {Label = "Mapabstimmungen-HUD anzeigen", Command = "cl_showvotemap"})
	CPanel:AddControl("CheckBox", {Label = "Geschwindigkeitsanzeige in Autos anzeigen", Command = "cl_speedometer"})
	CPanel:AddControl("Label", {Text = "Anzeige:"})
	CPanel:AddControl("CheckBox", {Label = "Waffenstatistiken beim Anschauen anzeigen", Command = "cl_drawweaponstats"})
	CPanel:AddControl("CheckBox", {Label = "Chatnachrichten über den Köpfen von Spielern", Command = "cl_renderchat"})
	CPanel:AddControl("CheckBox", {Label = "Trefferpunkteanzeige aktivieren", Command = "cl_hitnums_enable"})
	CPanel:AddControl("Slider", {Label = "Größe der Trefferpunkte", Command = "cl_hitnums_size", Type = "Float", Min = "0", Max = "1"})
	CPanel:AddControl("Slider", {Label = "Transparenz der Trefferpunkte", Command = "cl_hitnums_alpha", Type = "Float", Min = "0", Max = "1"})
	CPanel:AddControl("Slider", {Label = "Bleibelänge der Trefferpunkte", Command = "cl_hitnums_lifetime", Type = "Float", Min = "0", Max = "10"})
	CPanel:AddControl("CheckBox", {Label = "Hitmarker aktivieren", Command = "cl_hitmarker_enable"})
	CPanel:AddControl("CheckBox", {Label = "Ton bei Treffer abspielen", Command = "cl_hitmarker_hitsound"})
	CPanel:AddControl("CheckBox", {Label = "Nachricht, wenn ein Spieler dem Server beitritt", Command = "cl_connectmessages"})
	CPanel:AddControl("CheckBox", {Label = "Nachricht, wenn ein Spieler den Server verlässt", Command = "cl_disconnectmessages"})
	CPanel:AddControl("Label", {Text = "Build & Fight:"})
	CPanel:AddControl("CheckBox", {Label = "Klasse über F7 und F8 wechseln", Command = "bf_shortcuts"})
	CPanel:AddControl("CheckBox", {Label = "Informationsfenster bezüglich Klassenwechsel anzeigen", Command = "bf_shownotify"})
	CPanel:AddControl("CheckBox", {Label = "Tötungsbenachrichtigungen anzeigen", Command = "bf_showscreenmsg"})
	CPanel:AddControl("CheckBox", {Label = "Tötungsbenachrichtigungen minimieren", Command = "bf_supressscreenmsg"})
	CPanel:AddControl("CheckBox", {Label = "Alte Tötungsbenachrichtigungen verwenden", Command = "bf_old_message"})
	CPanel:AddControl("CheckBox", {Label = "Eigenes Pet verstecken", Command = "cl_pets_hide"})
	CPanel:AddControl("CheckBox", {Label = "Eigene Pet-Effekte verstecken", Command = "cl_pets_hideowneffects"})
	CPanel:AddControl("CheckBox", {Label = "Pet-Effekte verstecken", Command = "cl_pets_hideeffects"})
	CPanel:AddControl("Label", {Text = "Party:"})
	CPanel:AddControl("CheckBox", {Label = "Partyspielerlistung darstellen", Command = "cl_showparty"})
	CPanel:AddControl("CheckBox", {Label = "Ringe unter Partymitgliedern", Command = "cl_showpartyrings"})
	CPanel:AddControl("CheckBox", {Label = "Leben in der Partyspielerlistung anzeigen", Command = "cl_showpartyhealth"})
	CPanel:AddControl("CheckBox", {Label = "Größe der Partyspielerlistung limitieren", Command = "cl_limitpartypanels"})
	CPanel:AddControl("CheckBox", {Label = "Erweiterte Partyspielerlistung benutzen", Command = "cl_extendedpartypanels"})
	CPanel:AddControl("CheckBox", {Label = "Party-Einladungen automatisch ignorieren", Command = "cl_ignorepartyinvites"})
	CPanel:AddControl("CheckBox", {Label = "Party-Anfragen automatisch ignorieren", Command = "cl_ignorepartyasks"})
	CPanel:AddControl("Label", {Text = "Fadenkreuz:"})
	CPanel:AddControl("CheckBox", {Label = "Fadenkreuz für Waffen deaktivieren", Command = "mg_m9k_disable_crosshair"})
	CPanel:AddControl("CheckBox", {Label = "Standardmäßiges Fadenkreuz für Waffen benutzen", Command = "mg_m9k_alternate_crosshair"})
	CPanel:AddControl("Slider", {Label = "Fadenkreuz-Größe", Command = "mg_m9k_crosshair_size", Type = "Float", Min = "0.1", Max = "3"})
	CPanel:AddControl("Slider", {Label = "Fadenkreuz-Dicke", Command = "mg_m9k_crosshair_thickness", Type = "Float", Min = "0.1", Max = "1"})
	CPanel:AddControl("Slider", {Label = "Fadenkreuz-Zieltransparenz", Command = "mg_m9k_aiming_crosshair_opacity", Type = "Float", Min = "0", Max = "1"})
	CPanel:AddControl("Slider", {Label = "Fadenkreuz-Farbe (r)", Command = "mg_m9k_crosshair_color_r", Type = "Int", Min = "0", Max = "255"})
	CPanel:AddControl("Slider", {Label = "Fadenkreuz-Farbe (g)", Command = "mg_m9k_crosshair_color_g", Type = "Int", Min = "0", Max = "255"})
	CPanel:AddControl("Slider", {Label = "Fadenkreuz-Farbe (b)", Command = "mg_m9k_crosshair_color_b", Type = "Int", Min = "0", Max = "255"})
	CPanel:AddControl("Button", {Text = "Fadenkreuz zurücksetzen", Command = "mg_m9k_crosshair_reset"})
	CPanel:AddControl("Label", {Text = ""})
	CPanel:AddControl("Label", {Text = "Experimentell:"})
	CPanel:AddControl("CheckBox", {Label = "Multicore Rendering aktivieren", Command = "mg_multicore"})
	CPanel:AddControl("CheckBox", {Label = "Standardmäßig verwenden", Command = "mg_multicore_save"})
	CPanel:AddControl("Label", {Text = "Multicore Rendering sorgt dafür, dass alle CPU-Kerne voll ausgelastet werden.\nDie FPS verdoppelt sich oft bei Aktivierung.\nUnter bestimmten Vorraussetzungen oder Systemkonfigurationen, kann dies zu Spielabstürzen führen."})
	CPanel:AddControl("CheckBox", {Label = "3D Skybox zeichnen", Command = "r_3dsky"})
end

CreateClientConVar("mg_multicore", 0, false)
CreateClientConVar("mg_multicore_save", 0)

cvars.AddChangeCallback("mg_multicore", function(name, old, new)
	if tonumber(new) != 0 then
		RunConsoleCommand("cl_threaded_bone_setup", 1)
		RunConsoleCommand("cl_threaded_client_leaf_system", 1)
		RunConsoleCommand("r_threaded_client_shadow_manager", 1)
		RunConsoleCommand("r_threaded_particles", 1)
		RunConsoleCommand("r_threaded_renderables", 1)
		RunConsoleCommand("r_queued_ropes", 1)
		RunConsoleCommand("studio_queue_mode", 1)
		RunConsoleCommand("mat_queue_mode", -1)
		RunConsoleCommand("gmod_mcore_test", 1)
		--RunConsoleCommand("mod_load_anims_async", 1)
		--RunConsoleCommand("mod_load_mesh_async", 1)
		--RunConsoleCommand("mod_load_vcollide_async", 1)
	else
		RunConsoleCommand("gmod_mcore_test", 0)
		--RunConsoleCommand("mod_load_anims_async", 0)
		--RunConsoleCommand("mod_load_mesh_async", 0)
		--RunConsoleCommand("mod_load_vcollide_async", 0)
	end
end)

if GetConVar("mg_multicore_save"):GetBool() then
	RunConsoleCommand("mg_multicore", 1)
end

cvars.AddChangeCallback("mg_multicore_save", function(name, old, new)
	if (tonumber(new) or 0) != 0 then
		RunConsoleCommand("mg_multicore", 1)
	end
end)

local function PopulateOptionMenus()
	spawnmenu.AddToolMenuOption("Utilities", "Modern Gaming", "Einstellungen", "Einstellungen", "", "", ModernGamingOptions)
end
hook.Add("PopulateToolMenu", "ToolMenu_AddModernGamingSettings", PopulateOptionMenus)